# Yarn PnP and pnpm linkers break Prettier and ESLint plugin resolution for
# .astro files. Prettier uses import-meta-resolve which bypasses PnP
# (yarnpkg/berry#6167), and ESLint flat config has PnP SDK issues
# (yarnpkg/berry#6219). The pnpm linker's strict isolation causes the same
# failures for transitive deps like astro-eslint-parser.
nodeLinker: node-modules
